#pragma once

// Auto-generated binary resources from webapp/dist/index.html (single-file with inlined CSS/JS)
// Do not edit this file manually

// HTML resource functions (contains inlined CSS and JS)
const char* GetWebAppHTML();
unsigned int GetWebAppHTMLSize();

// Placeholder functions for compatibility (not used with single-file build)
const char* GetWebAppCSS();
unsigned int GetWebAppCSSSize();
const char* GetWebAppJS();
unsigned int GetWebAppJSSize();
